### ISSUE TITLE
Redline and Word with Track Changes options in APIs.

### ISSUE THREAD

**Issue by shakir-snakescript** [draftable/compare-api-python-client#4]
This tools is amazing and I was thinking about to purchase the apis. However, I was testing the APIs and I found only 4 options to export(left, right, combined and single_page). But I want the exported file as Redline PDF or Word with Track Changes kind of doc file.

The issue with the side by side view is only good in browser but not when you download it. Combined files combining the pdfs in a wrong way. It combines the files in alternative fashion by page numbers.

The thing I liked was Redline PDF and Word with Track Changes(these options are available in your downloadable software). How can I achieve that in APIs or using draftable library?

**Comment by cwroxburgh** [comment]
Hi @shakir-snakescript - I'm the Product Lead for Draftable. Thanks for sharing your feedback with us! 

As you've alluded to, we don't yet offer Draftable Legal (with our Redline PDF and Word with Tracked Changes outputs) via API. This is something we may develop in future but is off the cards for 2024 while we focus on core features for our Desktop Applications. That said, we'd love to learn more about your case for the Redline API. Please reach out at product@draftable.com and we can set up a time to discuss this further.

Regarding your feedback on the Side by Side export options, our export option for 'combined' is recommended and should appear in your PDF viewer (e.g. Acrobat) as a side by side style view. If you're having trouble with this we're happy to help via support@draftable.com. We are aware of some issues with this export not matching what is shown in our viewer and those are scheduled for improvement in the next few months.

**Comment by pablospe** [comment]
@shakir-snakescript Did you find a solution?

**Comment by cwroxburgh-product** [comment]
@pablospe redline outputs are not supported in the API product. They are only available in the Desktop App. The API product only performs side by side comparisons
